### ISSUE TITLE
Would it be possible to set up push rights for the maintainer - Takashi?

### ISSUE THREAD

**Issue by StephanPreibisch** [fiji/H5J_Loader_Plugin#4]
Hi @ctrueden, would that be ok with you?  takashi310 would like to help maintain this ...

**Comment by ctrueden** [comment]
@takashi310 I invited you as a maintainer!

@StephanPreibisch Do you need maintainer access as well?

**Comment by takashi310** [comment]
Thank you for giving me the maintainer access, @ctrueden and @StephanPreibisch! I appreciate it.

**Comment by StephanPreibisch** [comment]
Hi @ctrueden, no thanks ... I think @takashi310 is the right one :)
